begin;

create extension if not exists pgcrypto;

create table if not exists public.users_profile (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'Tracking',
  full_name text,
  phone text,
  is_approved boolean not null default false,
  is_blocked boolean not null default false,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text,
  agent_name text,
  agent_phone text,
  page_name text,
  page_number text,
  page_phone text,
  page_whatsapp text,
  page_id uuid,
  status text not null default 'معلق',
  awaiting_page_reply boolean not null default true,
  price numeric(10, 2) not null default 0,
  price_changed boolean not null default false,
  rejected_on_arrival boolean not null default false,
  has_issue boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists page_phone text;
alter table public.orders add column if not exists page_whatsapp text;
alter table public.orders add column if not exists page_id uuid;
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists agent_name text;
alter table public.orders add column if not exists price_changed boolean not null default false;

do $$
begin
  execute 'alter table public.orders add constraint orders_page_id_fkey foreign key (page_id) references public.users_profile(id) on delete set null';
exception
  when others then null;
end $$;

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  type text not null check (type in ('text', 'image', 'audio')),
  from_role text not null check (from_role in ('customer', 'agent', 'page', 'tracking')),
  text text,
  media_url text,
  audio_duration_sec integer,
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists by_name text;

drop function if exists public.lookup_login_email(text) cascade;

create or replace function public.lookup_login_email(p_identifier text)
returns text
language sql
stable
security definer
set search_path = public, auth
as $$
  with input as (
    select
      trim(coalesce(p_identifier, '')) as ident,
      regexp_replace(trim(coalesce(p_identifier, '')), '[^0-9]+', '', 'g') as digits
  )
  select u.email
  from public.users_profile p
  join auth.users u on u.id = p.id
  cross join input i
  where i.ident <> ''
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_blocked, false) = false
    and (
      (
        p.full_name is not null
        and trim(p.full_name) <> ''
        and lower(trim(p.full_name)) = lower(i.ident)
      )
      or (
        i.digits <> ''
        and p.phone is not null
        and regexp_replace(p.phone, '[^0-9]+', '', 'g') = i.digits
      )
    )
  limit 1;
$$;

drop function if exists public.admin_list_users() cascade;

create or replace function public.admin_list_users()
returns table (
  id uuid,
  full_name text,
  phone text,
  role text,
  is_approved boolean,
  is_blocked boolean,
  is_deleted boolean,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.full_name, p.phone, p.role, p.is_approved, p.is_blocked, p.is_deleted, p.created_at
  from public.users_profile p
  where exists (
    select 1
    from public.users_profile me
    where me.id = auth.uid()
      and me.role = 'Admin'
  )
  order by p.created_at desc;
$$;

drop function if exists public.admin_set_user_role(uuid, text) cascade;

create or replace function public.admin_set_user_role(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_admin_count integer;
  v_primary_admin uuid;
begin
  if not exists (
    select 1
    from public.users_profile me
    where me.id = auth.uid()
      and me.role = 'Admin'
  ) then
    raise exception 'not allowed';
  end if;

  select p.id into v_primary_admin
  from public.users_profile p
  where p.role = 'Admin'
    and coalesce(p.is_deleted, false) = false
  order by p.created_at asc
  limit 1;

  if p_user_id = auth.uid() then
    raise exception 'cannot change self role';
  end if;

  v_role := case when p_role is null then '' else trim(p_role) end;
  if v_role not in ('Admin', 'Tracking') then
    raise exception 'invalid role';
  end if;

  -- Prevent demoting the last admin.
  if v_role = 'Tracking' then
    if v_primary_admin is not null and p_user_id = v_primary_admin then
      raise exception 'cannot demote primary admin';
    end if;

    select count(*) into v_admin_count
    from public.users_profile
    where role = 'Admin'
      and coalesce(is_deleted, false) = false;

    if v_admin_count <= 1 then
      raise exception 'cannot demote last admin';
    end if;
  end if;

  update public.users_profile
  set role = v_role,
      -- If promoted to Admin, make sure it's not stuck in pending.
      is_approved = case when v_role = 'Admin' then true else is_approved end,
      updated_at = now()
  where id = p_user_id;
end;
$$;

drop function if exists public.admin_set_user_blocked(uuid, boolean) cascade;

create or replace function public.admin_set_user_blocked(p_user_id uuid, p_blocked boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.users_profile me
    where me.id = auth.uid()
      and me.role = 'Admin'
  ) then
    raise exception 'not allowed';
  end if;

  if p_user_id = auth.uid() then
    raise exception 'cannot block self';
  end if;

  if exists (
    select 1
    from public.users_profile t
    where t.id = p_user_id
      and t.role = 'Admin'
  ) then
    raise exception 'cannot block admin';
  end if;

  update public.users_profile
  set is_blocked = coalesce(p_blocked, false),
      updated_at = now()
  where id = p_user_id;
end;
$$;

drop function if exists public.admin_soft_delete_user(uuid) cascade;

create or replace function public.admin_soft_delete_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_primary_admin uuid;
begin
  if not exists (
    select 1
    from public.users_profile me
    where me.id = auth.uid()
      and me.role = 'Admin'
  ) then
    raise exception 'not allowed';
  end if;

  select p.id into v_primary_admin
  from public.users_profile p
  where p.role = 'Admin'
    and coalesce(p.is_deleted, false) = false
  order by p.created_at asc
  limit 1;

  if p_user_id = auth.uid() then
    raise exception 'cannot delete self';
  end if;

  if v_primary_admin is not null and p_user_id = v_primary_admin then
    raise exception 'cannot delete primary admin';
  end if;

  if exists (
    select 1
    from public.users_profile t
    where t.id = p_user_id
      and t.role = 'Admin'
  ) then
    raise exception 'cannot delete admin';
  end if;

  update public.users_profile
  set is_deleted = true,
      is_blocked = true,
      is_approved = false,
      updated_at = now()
  where id = p_user_id;
end;
$$;

grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_set_user_role(uuid, text) to authenticated;
grant execute on function public.admin_set_user_blocked(uuid, boolean) to authenticated;
grant execute on function public.admin_soft_delete_user(uuid) to authenticated;

create or replace function public.admin_list_pending_users()
returns table (id uuid, full_name text, phone text, created_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.full_name, p.phone, p.created_at
  from public.users_profile p
  where exists (
    select 1
    from public.users_profile me
    where me.id = auth.uid()
      and me.role = 'Admin'
  )
    and p.role = 'Tracking'
    and coalesce(p.is_approved, false) = false
    and coalesce(p.is_deleted, false) = false
  order by p.created_at desc;
$$;

drop function if exists public.admin_approve_user(uuid) cascade;

create or replace function public.admin_approve_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.users_profile me
    where me.id = auth.uid()
      and me.role = 'Admin'
  ) then
    raise exception 'not allowed';
  end if;

  update public.users_profile
  set is_approved = true,
      updated_at = now()
  where id = p_user_id;
end;
$$;

grant execute on function public.admin_list_pending_users() to authenticated;
grant execute on function public.admin_approve_user(uuid) to authenticated;

grant execute on function public.lookup_login_email(text) to anon;
grant execute on function public.lookup_login_email(text) to authenticated;

create index if not exists messages_order_id_created_at_idx
  on public.messages(order_id, created_at);

create table if not exists public.keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.keywords (keyword)
values
  ('مشكلة'),
  ('تأخير'),
  ('رفض'),
  ('عاجل'),
  ('لا يرد')
on conflict (keyword) do nothing;

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  status text not null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  action text not null,
  table_name text,
  record_pk text,
  old_data jsonb,
  new_data jsonb,
  meta jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_id_idx on public.audit_logs(actor_id);

create index if not exists order_status_history_order_id_created_at_idx
  on public.order_status_history(order_id, created_at);

drop function if exists public.set_updated_at() cascade;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_orders_set_updated_at on public.orders;
create trigger trg_orders_set_updated_at
before update on public.orders
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_users_profile_set_updated_at on public.users_profile;
create trigger trg_users_profile_set_updated_at
before update on public.users_profile
for each row execute procedure public.set_updated_at();

drop function if exists public.handle_new_user() cascade;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users_profile (id, role, full_name, phone, is_approved, is_blocked, is_deleted, created_at, updated_at)
  values (
    new.id,
    'Tracking',
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), ''),
    nullif(regexp_replace(coalesce(new.raw_user_meta_data ->> 'phone', ''), '[^0-9]+', '', 'g'), ''),
    false,
    false,
    false,
    now(),
    now()
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

drop function if exists public.log_order_created() cascade;

create or replace function public.log_order_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.order_status_history (order_id, status, note, created_at)
  values (new.id, new.status, 'تم إنشاء الطلب', now());
  return new;
end;
$$;

drop trigger if exists trg_orders_log_insert on public.orders;
create trigger trg_orders_log_insert
after insert on public.orders
for each row execute procedure public.log_order_created();

drop function if exists public.log_order_status_change() cascade;

create or replace function public.log_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status then
    insert into public.order_status_history (order_id, status, note, created_at)
    values (new.id, new.status, 'تحديث حالة الطلب', now());
  end if;

  return new;
end;
$$;

drop trigger if exists trg_orders_log_status_change on public.orders;
create trigger trg_orders_log_status_change
after update on public.orders
for each row execute procedure public.log_order_status_change();

drop function if exists public.detect_keyword(text) cascade;

create or replace function public.detect_keyword(p_text text)
returns text
language sql
stable
as $$
  select k.keyword
  from public.keywords k
  where k.is_active = true
    and p_text is not null
    and position(k.keyword in p_text) > 0
  order by length(k.keyword) desc
  limit 1;
$$;

drop function if exists public.handle_new_message() cascade;

create or replace function public.handle_new_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_keyword text;
begin
  if new.type = 'text' then
    v_keyword := public.detect_keyword(new.text);
  end if;

  update public.orders
  set updated_at = now(),
      awaiting_page_reply = case when new.from_role = 'page' then false else awaiting_page_reply end,
      has_issue = case when v_keyword is not null then true else has_issue end
  where id = new.order_id;

  return new;
end;
$$;

drop trigger if exists trg_messages_after_insert on public.messages;
create trigger trg_messages_after_insert
after insert on public.messages
for each row execute procedure public.handle_new_message();

drop function if exists public.audit_trigger() cascade;

create or replace function public.audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old jsonb;
  v_new jsonb;
  v_pk text;
begin
  v_old := null;
  v_new := null;
  v_pk := null;

  if tg_op = 'INSERT' then
    v_new := to_jsonb(new);
    v_pk := coalesce(v_new ->> 'order_id', v_new ->> 'id');
  elsif tg_op = 'UPDATE' then
    v_old := to_jsonb(old);
    v_new := to_jsonb(new);
    v_pk := coalesce(v_new ->> 'order_id', v_new ->> 'id');
  elsif tg_op = 'DELETE' then
    v_old := to_jsonb(old);
    v_pk := coalesce(v_old ->> 'order_id', v_old ->> 'id');
  end if;

  insert into public.audit_logs (actor_id, action, table_name, record_pk, old_data, new_data, meta)
  values (auth.uid(), tg_op, tg_table_name, v_pk, v_old, v_new, null);

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_orders_audit on public.orders;
create trigger trg_orders_audit
after insert or update or delete on public.orders
for each row execute procedure public.audit_trigger();

drop trigger if exists trg_messages_audit on public.messages;
create trigger trg_messages_audit
after insert or update or delete on public.messages
for each row execute procedure public.audit_trigger();

drop trigger if exists trg_keywords_audit on public.keywords;
create trigger trg_keywords_audit
after insert or update or delete on public.keywords
for each row execute procedure public.audit_trigger();

drop trigger if exists trg_users_profile_audit on public.users_profile;
create trigger trg_users_profile_audit
after insert or update or delete on public.users_profile
for each row execute procedure public.audit_trigger();

drop trigger if exists trg_order_status_history_audit on public.order_status_history;
create trigger trg_order_status_history_audit
after insert or update or delete on public.order_status_history
for each row execute procedure public.audit_trigger();

do $$
begin
  execute 'alter publication supabase_realtime add table public.orders';
exception
  when others then null;
end $$;

do $$
begin
  execute 'alter publication supabase_realtime add table public.messages';
exception
  when others then null;
end $$;

alter table public.orders replica identity full;
alter table public.messages replica identity full;

alter table public.users_profile enable row level security;
alter table public.orders enable row level security;
alter table public.messages enable row level security;
alter table public.keywords enable row level security;
alter table public.order_status_history enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists users_profile_select_own on public.users_profile;
create policy users_profile_select_own
on public.users_profile
for select
to authenticated
using (id = auth.uid());

drop policy if exists audit_logs_insert on public.audit_logs;
-- Read-only: منع إدخال سجلات عبر الواجهة.

drop policy if exists audit_logs_select_admin on public.audit_logs;
create policy audit_logs_select_admin
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profile p
    where p.id = auth.uid()
      and p.role = 'Admin'
  )
);

drop policy if exists users_profile_insert_own on public.users_profile;
-- Read-only: لا يوجد insert عبر الواجهة.

drop policy if exists users_profile_update_own on public.users_profile;
-- Read-only: لا يوجد update عبر الواجهة.

drop policy if exists orders_select_all on public.orders;
drop policy if exists orders_select_internal on public.orders;
drop policy if exists orders_select_page_own on public.orders;

create policy orders_select_all
on public.orders
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  )
);

drop policy if exists orders_insert_admin_agent on public.orders;
-- Read-only: لا يوجد insert عبر الواجهة.

drop policy if exists orders_update_admin_agent on public.orders;
-- Read-only: لا يوجد update عبر الواجهة.

drop policy if exists orders_delete_admin on public.orders;
-- Read-only: لا يوجد delete عبر الواجهة.

drop policy if exists messages_select_all on public.messages;
drop policy if exists messages_select_internal on public.messages;
drop policy if exists messages_select_page_own on public.messages;

create policy messages_select_all
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  )
);

drop policy if exists messages_insert_admin_agent on public.messages;
-- Read-only: لا يوجد insert عبر الواجهة.

drop policy if exists messages_insert_allowed on public.messages;

create policy messages_insert_allowed
on public.messages
for insert
to authenticated
with check (
  exists (
    select 1
    from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  )
);

drop policy if exists messages_update_admin on public.messages;
-- Read-only: لا يوجد update عبر الواجهة.

drop policy if exists messages_delete_admin on public.messages;
-- Read-only: لا يوجد delete عبر الواجهة.

drop function if exists public.tracking_add_message(bigint,text,text,text,integer) cascade;

create or replace function public.tracking_add_message(
  p_order_id bigint,
  p_type text,
  p_text text,
  p_media_url text,
  p_audio_duration_sec integer
)
returns table (
  id uuid,
  order_id bigint,
  type text,
  from_role text,
  by_name text,
  text text,
  media_url text,
  audio_duration_sec integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  ) then
    raise exception 'not allowed';
  end if;

  if p_type not in ('text','image','audio') then
    raise exception 'invalid type';
  end if;

  return query
  insert into public.messages as m (order_id, type, from_role, by_name, text, media_url, audio_duration_sec, created_at)
  values (
    p_order_id,
    p_type,
    'tracking',
    nullif(trim(coalesce((select up.full_name from public.users_profile up where up.id = auth.uid()), '')), ''),
    case when p_type = 'text' then nullif(p_text, '') else null end,
    case when p_type in ('image','audio') then nullif(p_media_url, '') else null end,
    case when p_type = 'audio' then p_audio_duration_sec else null end,
    now()
  )
  returning m.id, m.order_id, m.type, m.from_role, m.by_name, m.text, m.media_url, m.audio_duration_sec, m.created_at;
end;
$$;

grant execute on function public.tracking_add_message(bigint, text, text, text, integer) to authenticated;

drop function if exists public.tracking_log_resolution(bigint) cascade;

create or replace function public.tracking_log_resolution(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  ) then
    raise exception 'not allowed';
  end if;

  if p_order_id is null then
    raise exception 'missing order_id';
  end if;

  if exists (
    select 1
    from public.order_status_history h
    where h.order_id = p_order_id
      and h.status = 'تم حل المشكلة'
      and h.created_at > now() - interval '2 minutes'
  ) then
    return;
  end if;

  insert into public.order_status_history (order_id, status, note, created_at)
  values (p_order_id, 'تم حل المشكلة', 'تم حل المشكلة', now());
end;
$$;

grant execute on function public.tracking_log_resolution(bigint) to authenticated;

drop function if exists public.tracking_update_order_status(bigint, text) cascade;

create or replace function public.tracking_update_order_status(
  p_order_id bigint,
  p_status text
)
returns setof public.orders
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  ) then
    raise exception 'not allowed';
  end if;

  if p_order_id is null then
    raise exception 'missing order_id';
  end if;

  if p_status is null or trim(p_status) = '' then
    raise exception 'missing status';
  end if;

  return query
  update public.orders o
  set status = trim(p_status)
  where o.id = p_order_id
  returning o.*;
end;
$$;

grant execute on function public.tracking_update_order_status(bigint, text) to authenticated;

drop function if exists public._normalize_msg_text(text) cascade;

create or replace function public._normalize_msg_text(p_text text)
returns text
language sql
immutable
as $$
  select lower(trim(coalesce(p_text, '')));
$$;

drop function if exists public.infer_order_status_from_message(text, text) cascade;

create or replace function public.infer_order_status_from_message(
  p_from_role text,
  p_text text
)
returns table (
  status text,
  set_rejected_on_arrival boolean,
  set_has_issue boolean
)
language plpgsql
immutable
as $$
declare
  t text;
  r text;
begin
  t := public._normalize_msg_text(p_text);
  r := lower(trim(coalesce(p_from_role, '')));

  if t = '' then
    return;
  end if;

  if r = 'agent' then
    if t ~ '(وصلت|تم\s*التسليم|سلمت|تم\s*التوصيل|تم\s*الاستلام|استلم|استلم\s*الطلب|تم\s*توصيل\s*الطلب|وصل\s*الطلب|وصلت\s*للعميل|الطلب\s*وصل|تم\s*التسليم\s*بنجاح|تم\s*تسليم\s*الطلب|delivery\s*done|delivered|livr[eé]|livraison\s*faite|done|complete|completed)'
    then
      status := 'تم التسليم';
      set_rejected_on_arrival := false;
      set_has_issue := false;
      return next;
      return;
    end if;

    if t ~ '(رفض\b|رفض\s*الاستلام|الزبون\s*رفض|العميل\s*رفض|رفض\s*عند\s*الوصول|رفض\s*الطلب|ما\s*حبش\s*يستلم|ما\s*قبلش\s*الطلب|رفض\s*الباب|رجع\s*الطلب|مرجع|returned|refused|client\s*refused|رفض\s*المنتج|العميل\s*غير\s*رأيه)'
    then
      status := 'رفض عند الوصول';
      set_rejected_on_arrival := true;
      set_has_issue := false;
      return next;
      return;
    end if;

    if t ~ '(خرجت|في\s*الطريق|جاري\s*التوصيل|بالطريق|متجه\s*للعميل|قيد\s*التوصيل|سيتم\s*التوصيل|طريقه\s*للعميل|انطلقت|في\s*التوصيل|going|on\s*the\s*way|out\s*for\s*delivery|en\s*route|delivery\s*started)'
    then
      status := 'جاري التوصيل';
      set_rejected_on_arrival := false;
      set_has_issue := false;
      return next;
      return;
    end if;

    if t ~ '(مشكلة|ما\s*يرد|ما\s*يجاوب|لا\s*يرد|الهاتف\s*مغلق|\bمغلق\b|الرقم\s*مغلق|رقم\s*خطأ|الرقم\s*غير\s*صحيح|لا\s*يمكن\s*الاتصال|unreachable|no\s*answer|wrong\s*number|invalid\s*number|الزبون\s*غير\s*متوفر|العميل\s*غير\s*موجود|العنوان\s*خطأ|العنوان\s*غير\s*واضح|لم\s*نجد\s*العنوان|تأجيل|مؤجل)'
    then
      status := 'مشكلة';
      set_rejected_on_arrival := false;
      set_has_issue := true;
      return next;
      return;
    end if;
  elsif r = 'page' then
    if t ~ '(تم\s*التأكيد|confirmed|تأكيد\s*الطلب|تم\s*تأكيد\s*الطلب|الطلب\s*مؤكد|تم\s*تسجيل\s*الطلب|تم\s*إنشاء\s*الطلب|order\s*confirmed|validated|accepted|approved)'
    then
      status := 'قيد التنفيذ';
      set_rejected_on_arrival := false;
      set_has_issue := false;
      return next;
      return;
    end if;

    if t ~ '(إلغاء|الغاء|تم\s*الإلغاء|الطلب\s*ملغي|إلغاء\s*الطلب|cancel|cancelled|canceled|order\s*cancelled|تم\s*الغاء\s*الطلب)'
    then
      status := 'ملغي';
      set_rejected_on_arrival := false;
      set_has_issue := false;
      return next;
      return;
    end if;
  elsif r = 'customer' then
    if t ~ '(إلغاء|الغاء\s*الطلب|ألغيت\s*الطلب|ما\s*عاد\s*نحب\s*الطلب|ما\s*نحبش\s*الطلب|cancel|cancel\s*order|ألغيه|مش\s*حاب\s*الطلب)'
    then
      status := 'ملغي';
      set_rejected_on_arrival := false;
      set_has_issue := false;
      return next;
      return;
    end if;

    if t ~ '(رفض|رفض\s*الطلب|ما\s*نحبش\s*نستلم|لا\s*أريد\s*الطلب|لا\s*أريده|ما\s*نريده|ما\s*نحبش|رفض\s*الاستلام|ما\s*نحبش\s*الطلب)'
    then
      status := 'مرفوض';
      set_rejected_on_arrival := false;
      set_has_issue := false;
      return next;
      return;
    end if;
  end if;

  return;
end;
$$;

drop function if exists public.messages_auto_update_order_status() cascade;

create or replace function public.messages_auto_update_order_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  inf record;
begin
  if new.order_id is null then
    return new;
  end if;

  select * into inf
  from public.infer_order_status_from_message(new.from_role, new.text)
  limit 1;

  if inf is null or inf.status is null or trim(inf.status) = '' then
    return new;
  end if;

  update public.orders o
  set status = inf.status,
      rejected_on_arrival = case when coalesce(inf.set_rejected_on_arrival, false) then true else o.rejected_on_arrival end,
      has_issue = case when coalesce(inf.set_has_issue, false) then true else o.has_issue end
  where o.id = new.order_id
    and (o.status is distinct from inf.status);

  return new;
end;
$$;

drop trigger if exists trg_messages_auto_update_order_status on public.messages;
create trigger trg_messages_auto_update_order_status
after insert on public.messages
for each row execute procedure public.messages_auto_update_order_status();

drop policy if exists keywords_select_all on public.keywords;
create policy keywords_select_all
on public.keywords
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profile up
    where up.id = auth.uid()
  )
);

drop policy if exists keywords_admin_write on public.keywords;
-- Read-only: لا توجد صلاحيات كتابة.

drop policy if exists order_status_history_select_all on public.order_status_history;
drop policy if exists order_status_history_select_internal on public.order_status_history;
drop policy if exists order_status_history_select_page_own on public.order_status_history;

create policy order_status_history_select_all
on public.order_status_history
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profile up
    where up.id = auth.uid()
      and (
        up.role = 'Admin'
        or (up.role = 'Tracking' and up.is_approved = true and up.is_blocked = false and up.is_deleted = false)
      )
  )
);

drop policy if exists order_status_history_insert_admin_agent on public.order_status_history;
-- Read-only: لا يوجد insert عبر الواجهة.

commit;
